apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "creality2mqtt.fullname" . }}
  labels:
    {{- include "creality2mqtt.labels" . | nindent 4 }}
  {{- if .Values.annotations}}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "creality2mqtt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "creality2mqtt.selectorLabels" . | nindent 8 }}
        {{- if .Values.podAnnotations}}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
      annotations: {{- if .Values.podAnnotations}}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: creality2mqtt
          image: "{{ include "creality2mqtt.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--ws-url={{ .Values.cfg.wsUrl }}"
            - "--mqtt-broker={{ .Values.cfg.mqttBroker }}"
            - "--mqtt-base-topic={{ .Values.cfg.mqttBaseTopic }}"
            - "--mqtt-min-interval={{ .Values.cfg.mqttMinInterval }}"
            - "--log-level={{ .Values.cfg.logLevel }}"
          env:
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.resources}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{ if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{ if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{ if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
